-- waywall MCSR engine.
--
-- This file is data-driven: `init.lua` (generated by the Nix home-manager
-- module in nix/modules/waywall.nix) builds a `cfg` table and calls the
-- function returned from here with it. Nothing in this file should need to be
-- edited to change colours, geometry or keybinds -- those all live in Nix.
--
-- Everything is laid out in *canvas* coordinates, i.e. the pixel grid of the
-- waywall window itself (cfg.canvas), not of the Minecraft render target.
-- waywall composites the instance 1:1 into the canvas and centres it
-- (server/ui.c:layout_centered), cropping if it overflows, so the on-screen
-- rectangle of the game for a WxH resolution is always
--   x = (canvas_w - W) / 2, w = min(W, canvas_w)
--   y = (canvas_h - H) / 2, h = min(H, canvas_h)
-- The Nix side computes the border overlays from exactly that formula.

local waywall = require("waywall")
local helpers = require("waywall.helpers")

return function(cfg)
	----------------------------------------------------------------------
	-- Base configuration table handed back to waywall
	----------------------------------------------------------------------

	-- Keyboard layout is persisted to a file rather than held in memory:
	-- flipping it rewrites the file and waywall's hot-reload picks the new
	-- value up on the next config load. Live `set_keymap` would be lighter,
	-- but a reload also re-applies the remap table, which is what makes the
	-- MCSR layout and its remaps switch as one unit.
	local read_layout = function()
		local file = io.open(cfg.layout_state_file, "r")
		if not file then
			return "mcsr"
		end
		local state = file:read("*a")
		file:close()
		return (state and state:gsub("%s+$", "") == "alt") and "alt" or "mcsr"
	end

	local layout = read_layout()

	local write_layout = function(new)
		local file = io.open(cfg.layout_state_file, "w")
		if not file then
			return
		end
		file:write(new)
		file:close()
	end

	local config = {
		input = {
			sensitivity = cfg.sensitivity.base,
			repeat_rate = cfg.repeat_rate,
			repeat_delay = cfg.repeat_delay,
			confine_pointer = cfg.confine_pointer,
		},
		theme = {
			background = cfg.colors.background,
			ninb_anchor = cfg.ninb.anchor,
			ninb_opacity = cfg.ninb.opacity,
		},
		window = {
			fullscreen_width = cfg.canvas.w,
			fullscreen_height = cfg.canvas.h,
		},
	}

	if layout == "mcsr" then
		config.input.layout = cfg.layouts.mcsr.layout
		config.input.variant = cfg.layouts.mcsr.variant
		config.input.remaps = cfg.layouts.mcsr.remaps
	else
		config.input.layout = cfg.layouts.alt.layout
		config.input.variant = cfg.layouts.alt.variant
		config.input.remaps = cfg.layouts.alt.remaps
	end

	----------------------------------------------------------------------
	-- Scene object helpers
	--
	-- waywall scene objects (mirrors, images, text) cannot be created during
	-- startup, only from an action or a `load` listener. These wrappers hold
	-- the handle so a single boolean drives create/destroy.
	----------------------------------------------------------------------

	local make_toggle = function(create)
		local this = nil

		return function(enable)
			if enable and not this then
				this = create()
			elseif this and not enable then
				this:close()
				this = nil
			end
		end
	end

	local make_image = function(path, dst, depth)
		return make_toggle(function()
			return waywall.image(path, { dst = dst, depth = depth })
		end)
	end

	local make_mirror = function(options)
		return make_toggle(function()
			return waywall.mirror(options)
		end)
	end

	-- One logical mirror per colour key: waywall's color_key keeps only pixels
	-- of `input` and repaints them `output`, so an N-colour recolour is N
	-- stacked mirrors of the same source rect.
	local make_keyed_mirrors = function(src, dst, depth, keys)
		local layers = {}
		for _, key in ipairs(keys) do
			table.insert(layers, make_mirror({ src = src, dst = dst, depth = depth, color_key = key }))
		end

		return function(enable)
			for _, layer in ipairs(layers) do
				layer(enable)
			end
		end
	end

	----------------------------------------------------------------------
	-- Colour keys
	--
	-- The `gameRenderer` pie chart draws each section in a fixed palette. The
	-- five entries below are the sections that matter for tall/thin BT
	-- (block entities, unspecified, destroyProgress, prepare, entities); the
	-- percentage text next to the chart uses very slightly different shades,
	-- hence the second table.
	----------------------------------------------------------------------

	local pie_keys = {
		{ input = "#EC6E4E", output = cfg.colors.pie_1 },
		{ input = "#46CE66", output = cfg.colors.pie_2 },
		{ input = "#CC6C46", output = cfg.colors.pie_2 },
		{ input = "#464C46", output = cfg.colors.pie_2 },
		{ input = "#E446C4", output = cfg.colors.pie_3 },
	}

	local percent_keys = {
		{ input = "#E96D4D", output = cfg.percent_match_text and cfg.colors.text or cfg.colors.pie_1 },
		{ input = "#45CB65", output = cfg.percent_match_text and cfg.colors.text or cfg.colors.pie_2 },
	}

	----------------------------------------------------------------------
	-- Geometry
	----------------------------------------------------------------------

	local thin = cfg.res.thin
	local tall = cfg.res.tall

	local panel = cfg.panel

	-- Pie chart. The chart itself is 340x178 of source pixels; with colour
	-- keying on, the percentage labels underneath are dropped from the source
	-- rect and mirrored separately (below) so they can be positioned and
	-- scaled independently. Destination is 420x423 at scale 1 -- the extra
	-- height is deliberate vertical stretch that turns the game's squashed
	-- ellipse back into a circle.
	local pie_src_thin = { x = thin.w - 340, y = thin.h - 406, w = 340, h = 178 }
	local pie_src_tall = { x = 44, y = tall.h - 406, w = 340, h = 178 }
	local pie_dst = {
		x = panel.pie.x,
		y = panel.pie.y,
		w = math.floor(420 * panel.pie.scale),
		h = math.floor(423 * panel.pie.scale),
	}

	local percent_src_thin = { x = thin.w - 93, y = thin.h - 221, w = 33, h = 25 }
	local percent_src_tall = { x = 291, y = tall.h - 221, w = 33, h = 25 }
	local percent_dst = {
		x = panel.percent.x,
		y = panel.percent.y,
		w = math.floor(33 * panel.percent.scale),
		h = math.floor(25 * panel.percent.scale),
	}

	-- F3 ender-eye count. The narrow source rect is the "E: n/m" line without
	-- the leading "C:" chunk-cache figure; `show_chunk_cache` widens it to
	-- include that line as well.
	local ecount_src = panel.ecount.show_chunk_cache and { x = 1, y = 28, w = 49, h = 18 }
		or { x = 13, y = 37, w = 37, h = 9 }
	local ecount_dst = {
		x = panel.ecount.x,
		y = panel.ecount.y,
		w = math.floor(ecount_src.w * panel.ecount.scale),
		h = math.floor(ecount_src.h * panel.ecount.scale),
	}

	-- Boat-eye measuring window: a thin vertical slice through the centre of
	-- the tall render, blown up to a 16:9 rectangle so the generated pixel
	-- ruler overlay (which is authored on a 16:9 canvas) lands on it 1:1.
	local measure_src = {
		x = math.floor((tall.w - cfg.measure.src_w) / 2),
		y = math.floor((tall.h - cfg.measure.src_h) / 2),
		w = cfg.measure.src_w,
		h = cfg.measure.src_h,
	}
	local measure_dst = cfg.measure.dst

	----------------------------------------------------------------------
	-- Scene objects
	----------------------------------------------------------------------

	local scene = {
		-- Borders are drawn under everything else (depth 1) so mirrors and
		-- text sit on top of them.
		border_thin = make_image(cfg.assets.border_thin, cfg.canvas_rect, 1),
		border_wide = make_image(cfg.assets.border_wide, cfg.canvas_rect, 1),
		border_tall = make_image(cfg.assets.border_tall, cfg.canvas_rect, 1),
		border_tall_bare = make_image(cfg.assets.border_tall_bare, cfg.canvas_rect, 1),

		measure = make_mirror({ src = measure_src, dst = measure_dst, depth = 2 }),
		measure_ruler = make_image(cfg.assets.measure_overlay, measure_dst, 3),

		ecount_thin = make_keyed_mirrors(ecount_src, ecount_dst, 2, {
			{ input = "#DDDDDD", output = cfg.colors.text },
		}),
		ecount_tall = make_keyed_mirrors(ecount_src, ecount_dst, 2, {
			{ input = "#DDDDDD", output = cfg.colors.text },
		}),

		pie_thin = make_keyed_mirrors(pie_src_thin, pie_dst, 2, pie_keys),
		pie_tall = make_keyed_mirrors(pie_src_tall, pie_dst, 2, pie_keys),

		percent_thin = make_keyed_mirrors(percent_src_thin, percent_dst, 3, percent_keys),
		percent_tall = make_keyed_mirrors(percent_src_tall, percent_dst, 3, percent_keys),

		crosshair = make_image(cfg.assets.crosshair, cfg.crosshair_rect, 4),
	}

	----------------------------------------------------------------------
	-- Modes
	--
	-- `tall` and `lowest` share a resolution (384x16384) and differ only in
	-- which overlays come up, which is why the mode is tracked explicitly
	-- instead of derived from `waywall.active_res()` via helpers.res_mirror.
	----------------------------------------------------------------------

	local show = function(mode)
		local is_thin = mode == "thin"
		local is_tall = mode == "tall"
		local is_lowest = mode == "lowest"
		local is_wide = mode == "wide"
		local any_tall = is_tall or is_lowest

		scene.border_thin(is_thin)
		scene.border_wide(is_wide)
		scene.border_tall(is_tall)
		scene.border_tall_bare(is_lowest)

		-- Boat eye is a tall-only tool, and pointless in `lowest` (which
		-- exists to read the pie chart at minimum render cost).
		scene.measure(is_tall)
		scene.measure_ruler(is_tall)

		scene.ecount_thin(is_thin)
		scene.ecount_tall(any_tall)

		scene.pie_thin(is_thin)
		scene.pie_tall(any_tall)

		scene.percent_thin(is_thin)
		scene.percent_tall(any_tall)
	end

	-- Resolution feed for the OBS resize animation script
	-- (resize_animation_waywall.py reads this file and tweens the capture
	-- transform). The 17ms sleep lets OBS observe the write one frame before
	-- the game actually resizes, which is what makes the tween start clean.
	local publish_res = function(w, h)
		if not cfg.resize_animation then
			return
		end
		os.execute(string.format('echo "%dx%d" > %q', w, h, cfg.res_state_file))
		waywall.sleep(17)
	end

	local make_res = function(mode, res, sens)
		return function()
			local active_w, active_h = waywall.active_res()

			if active_w == res.w and active_h == res.h then
				publish_res(cfg.canvas.w, cfg.canvas.h)
				waywall.set_resolution(0, 0)
				-- 0 means "reset to input.sensitivity", not "freeze the camera".
				waywall.set_sensitivity(0)
				show(nil)
			else
				publish_res(res.w, res.h)
				waywall.set_resolution(res.w, res.h)
				waywall.set_sensitivity(sens or 0)
				show(mode)
			end
		end
	end

	----------------------------------------------------------------------
	-- Side processes
	----------------------------------------------------------------------

	local running = function(pattern)
		local handle = io.popen("pgrep -f " .. string.format("%q", pattern))
		if not handle then
			return false
		end
		local result = handle:read("*l")
		handle:close()
		return result ~= nil
	end

	local toggle_ninbot = function()
		if not running(cfg.ninb.process) then
			waywall.exec(cfg.ninb.command)
			waywall.show_floating(true)
		else
			helpers.toggle_floating()
		end
	end

	-- The CPS counter is a wlr-layer-shell client of the *host* compositor, not
	-- of waywall, so it floats above the waywall window rather than inside it.
	-- That also means it is not a floating view waywall can show/hide, hence
	-- start/stop rather than a visibility toggle.
	local toggle_cps = function()
		if running(cfg.cps.process) then
			os.execute("pkill -f " .. string.format("%q", cfg.cps.process))
		else
			waywall.exec(cfg.cps.command)
		end
	end

	local crosshair_shown = false
	local toggle_crosshair = function()
		crosshair_shown = not crosshair_shown
		scene.crosshair(crosshair_shown)
	end

	----------------------------------------------------------------------
	-- Keybinds
	----------------------------------------------------------------------

	local keys = cfg.keys

	config.actions = {
		[keys.thin] = make_res("thin", cfg.res.thin, cfg.sensitivity.thin),
		[keys.wide] = make_res("wide", cfg.res.wide, cfg.sensitivity.wide),
		[keys.tall] = make_res("tall", cfg.res.tall, cfg.sensitivity.tall),
		[keys.lowest] = make_res("lowest", cfg.res.tall, cfg.sensitivity.tall),

		[keys.switch_layout] = function()
			write_layout(layout == "mcsr" and "alt" or "mcsr")
			print("switching keyboard layout; waiting for config reload")
		end,

		[keys.ninbot] = toggle_ninbot,
		[keys.cps] = toggle_cps,
		[keys.crosshair] = toggle_crosshair,
	}

	if cfg.paceman.enable then
		config.actions[keys.paceman] = function()
			if running(cfg.paceman.process) then
				print("paceman-tracker already running")
			else
				waywall.exec(cfg.paceman.command)
			end
		end
	end

	return config
end
