-- waywall MCSR engine.
--
-- This file is data-driven: `init.lua` (generated by the Nix home-manager
-- module in nix/modules/waywall.nix) builds a `cfg` table and calls the
-- function returned from here with it. Nothing in this file should need to be
-- edited to change colours, geometry or keybinds -- those all live in Nix.
--
-- Everything is laid out in *canvas* coordinates, i.e. the pixel grid of the
-- waywall window itself (cfg.canvas), not of the Minecraft render target.
-- waywall composites the instance 1:1 into the canvas and centres it
-- (server/ui.c:layout_centered), cropping if it overflows, so the on-screen
-- rectangle of the game for a WxH resolution is always
--   x = (canvas_w - W) / 2, w = min(W, canvas_w)
--   y = (canvas_h - H) / 2, h = min(H, canvas_h)
-- The Nix side computes the border overlays from exactly that formula.

local waywall = require("waywall")
local helpers = require("waywall.helpers")

return function(cfg)
	----------------------------------------------------------------------
	-- Base configuration table handed back to waywall
	----------------------------------------------------------------------

	-- Keyboard layout is persisted to a file rather than held in memory:
	-- flipping it rewrites the file and waywall's hot-reload picks the new
	-- value up on the next config load. Live `set_keymap` would be lighter,
	-- but a reload also re-applies the remap table, which is what makes the
	-- MCSR layout and its remaps switch as one unit.
	local read_layout = function()
		local file = io.open(cfg.layout_state_file, "r")
		if not file then
			return "mcsr"
		end
		local state = file:read("*a")
		file:close()
		return (state and state:gsub("%s+$", "") == "alt") and "alt" or "mcsr"
	end

	local layout = read_layout()

	local write_layout = function(new)
		local file = io.open(cfg.layout_state_file, "w")
		if not file then
			return
		end
		file:write(new)
		file:close()
	end

	local config = {
		input = {
			sensitivity = cfg.sensitivity.base,
			repeat_rate = cfg.repeat_rate,
			repeat_delay = cfg.repeat_delay,
			confine_pointer = cfg.confine_pointer,
		},
		theme = {
			background = cfg.colors.background,
			ninb_anchor = cfg.ninb.anchor,
			ninb_opacity = cfg.ninb.opacity,
		},
		window = {
			fullscreen_width = cfg.canvas.w,
			fullscreen_height = cfg.canvas.h,
		},
	}

	if layout == "mcsr" then
		config.input.layout = cfg.layouts.mcsr.layout
		config.input.variant = cfg.layouts.mcsr.variant
		config.input.remaps = cfg.layouts.mcsr.remaps
	else
		config.input.layout = cfg.layouts.alt.layout
		config.input.variant = cfg.layouts.alt.variant
		config.input.remaps = cfg.layouts.alt.remaps
	end

	----------------------------------------------------------------------
	-- Scene object helpers
	--
	-- waywall scene objects (mirrors, images, text) cannot be created during
	-- startup, only from an action or a `load` listener. These wrappers hold
	-- the handle so a single boolean drives create/destroy.
	----------------------------------------------------------------------

	local make_toggle = function(create)
		local this = nil

		return function(enable)
			if enable and not this then
				this = create()
			elseif this and not enable then
				this:close()
				this = nil
			end
		end
	end

	local make_image = function(path, dst, depth)
		return make_toggle(function()
			return waywall.image(path, { dst = dst, depth = depth })
		end)
	end

	local make_mirror = function(options)
		return make_toggle(function()
			return waywall.mirror(options)
		end)
	end

	-- One logical mirror per colour key: waywall's color_key keeps only pixels
	-- of `input` and repaints them `output`, so an N-colour recolour is N
	-- stacked mirrors of the same source rect.
	local make_keyed_mirrors = function(src, dst, depth, keys)
		local layers = {}
		for _, key in ipairs(keys) do
			table.insert(layers, make_mirror({ src = src, dst = dst, depth = depth, color_key = key }))
		end

		return function(enable)
			for _, layer in ipairs(layers) do
				layer(enable)
			end
		end
	end

	----------------------------------------------------------------------
	-- Colour keys
	--
	-- The `gameRenderer` pie chart draws each section in a fixed palette. The
	-- five entries below are the sections that matter for tall/thin BT
	-- (block entities, unspecified, destroyProgress, prepare, entities); the
	-- percentage text next to the chart uses very slightly different shades,
	-- hence the second table.
	----------------------------------------------------------------------

	local pie_keys = {
		{ input = "#EC6E4E", output = cfg.colors.pie_1 },
		{ input = "#46CE66", output = cfg.colors.pie_2 },
		{ input = "#CC6C46", output = cfg.colors.pie_2 },
		{ input = "#464C46", output = cfg.colors.pie_2 },
		{ input = "#E446C4", output = cfg.colors.pie_3 },
	}

	local percent_keys = {
		{ input = "#E96D4D", output = cfg.percent_match_text and cfg.colors.text or cfg.colors.pie_1 },
		{ input = "#45CB65", output = cfg.percent_match_text and cfg.colors.text or cfg.colors.pie_2 },
	}

	----------------------------------------------------------------------
	-- Geometry
	----------------------------------------------------------------------

	local tall = cfg.res.tall

	local panel = cfg.panel

	-- Pie chart and percentage source rects, as a function of the render
	-- resolution. Minecraft anchors the profiler chart to the bottom-left of the
	-- window and the percentage list to the bottom-right, so both are a fixed
	-- offset from the far edges whatever the resolution is -- which is why these
	-- are derived rather than written out per mode.
	--
	-- The chart is 340x178 source pixels. With colour keying on, the percentage
	-- labels underneath fall outside this rect and are mirrored separately
	-- (below) so they can be placed and scaled on their own.
	local pie_src = function(res)
		return { x = res.w - 340, y = res.h - 406, w = 340, h = 178 }
	end
	local percent_src = function(res)
		return { x = res.w - 93, y = res.h - 221, w = 33, h = 25 }
	end

	-- Destination is 420x423 at scale 1 -- the extra height over the 178px source
	-- is deliberate vertical stretch, turning the game's squashed ellipse back
	-- into a circle.
	local pie_dst = {
		x = panel.pie.x,
		y = panel.pie.y,
		w = math.floor(420 * panel.pie.scale),
		h = math.floor(423 * panel.pie.scale),
	}

	local percent_dst = {
		x = panel.percent.x,
		y = panel.percent.y,
		w = math.floor(33 * panel.percent.scale),
		h = math.floor(25 * panel.percent.scale),
	}

	-- F3 ender-eye count. The narrow source rect is the "E: n/m" line without
	-- the leading "C:" chunk-cache figure; `show_chunk_cache` widens it to
	-- include that line as well.
	local ecount_src = panel.ecount.show_chunk_cache and { x = 1, y = 28, w = 49, h = 18 }
		or { x = 13, y = 37, w = 37, h = 9 }
	local ecount_dst = {
		x = panel.ecount.x,
		y = panel.ecount.y,
		w = math.floor(ecount_src.w * panel.ecount.scale),
		h = math.floor(ecount_src.h * panel.ecount.scale),
	}

	-- Boat-eye measuring window: a thin vertical slice through the centre of
	-- the tall render, blown up to a 16:9 rectangle so the generated pixel
	-- ruler overlay (which is authored on a 16:9 canvas) lands on it 1:1.
	local measure_src = {
		x = math.floor((tall.w - cfg.measure.src_w) / 2),
		y = math.floor((tall.h - cfg.measure.src_h) / 2),
		w = cfg.measure.src_w,
		h = cfg.measure.src_h,
	}
	local measure_dst = cfg.measure.dst

	----------------------------------------------------------------------
	-- Scene objects
	----------------------------------------------------------------------

	local scene = {
		-- Borders are drawn under everything else (depth 1) so mirrors and
		-- text sit on top of them. Frames (which depend on the resolution) and
		-- panels (which depend on what is in them) are separate images so they
		-- can be combined freely.
		frame_thin = make_image(cfg.assets.frame_thin, cfg.canvas_rect, 1),
		frame_wide = make_image(cfg.assets.frame_wide, cfg.canvas_rect, 1),
		frame_tall = make_image(cfg.assets.frame_tall, cfg.canvas_rect, 1),
		frame_lowest = make_image(cfg.assets.frame_lowest, cfg.canvas_rect, 1),

		panel_full = make_image(cfg.assets.panel_full, cfg.canvas_rect, 1),
		panel_ecount = make_image(cfg.assets.panel_ecount, cfg.canvas_rect, 1),

		measure = make_mirror({ src = measure_src, dst = measure_dst, depth = 2 }),
		measure_ruler = make_image(cfg.assets.measure_overlay, measure_dst, 3),

		-- Depth 4, above both the mirror and the ruler, because this frame has to
		-- paint *over* what it frames. The game-viewport frames get away with
		-- depth 1 only because the Minecraft surface sits below every
		-- positive-depth scene object; a mirror does not, so a mask drawn under
		-- one would be hidden by it and the mirror's square corners would still
		-- show past the rounded border.
		measure_frame = make_image(cfg.assets.frame_measure, cfg.canvas_rect, 4),

		crosshair = make_image(cfg.assets.crosshair, cfg.crosshair_rect, 5),
	}

	-- One set of instrument mirrors per resolution that has them. The e-count
	-- source rect is the same everywhere (the debug text is anchored top-left),
	-- but the pie and percentages move with the far edges of the window.
	local instruments = {}
	for _, name in ipairs({ "thin", "tall", "lowest" }) do
		local res = cfg.res[name]

		instruments[name] = {
			ecount = make_keyed_mirrors(ecount_src, ecount_dst, 2, {
				{ input = "#DDDDDD", output = cfg.colors.text },
			}),
			pie = make_keyed_mirrors(pie_src(res), pie_dst, 2, pie_keys),
			percent = make_keyed_mirrors(percent_src(res), percent_dst, 3, percent_keys),
		}
	end

	----------------------------------------------------------------------
	-- Modes
	--
	-- `tall` and `lowest` share a resolution (384x16384) and differ only in
	-- which overlays come up, which is why the mode is tracked explicitly
	-- instead of derived from `waywall.active_res()` via helpers.res_mirror.
	----------------------------------------------------------------------

	-- Which panel frame to draw. Sizing it to what the mirrors are *actually*
	-- picking up is not possible: waywall's Lua API has no way to read back what
	-- a mirror is sampling. Mirrors expose only close/get_depth/set_depth, and
	-- none of the module's other functions touch pixel contents, so nothing can
	-- distinguish "the profiler chart is up" from "that region of the game is
	-- empty". Hence a configured choice rather than a detected one.
	--
	--   "full"   -- always frame the whole cluster
	--   "ecount" -- always frame just the counter, and leave the pie unframed
	--   "none"   -- no panel frame at all
	local frame_mode = cfg.panel.frame

	local mode = nil

	local show = function(new_mode)
		mode = new_mode

		local is_thin = mode == "thin"
		local is_tall = mode == "tall"
		local is_lowest = mode == "lowest"
		local is_wide = mode == "wide"
		local any_res = is_thin or is_tall or is_lowest

		scene.frame_thin(is_thin)
		scene.frame_wide(is_wide)
		scene.frame_tall(is_tall)
		scene.frame_lowest(is_lowest)

		-- Boat eye is a tall-only tool, and pointless in `lowest` (which exists
		-- to read the pie chart at a smaller render).
		scene.measure(is_tall)
		scene.measure_ruler(is_tall)
		scene.measure_frame(is_tall)

		scene.panel_full(any_res and frame_mode == "full")
		scene.panel_ecount(any_res and frame_mode == "ecount")

		for name, set in pairs(instruments) do
			local active = mode == name
			set.ecount(active)
			set.pie(active)
			set.percent(active)
		end
	end

	-- Resolution feed for the OBS resize animation script
	-- (resize_animation_waywall.py reads this file and tweens the capture
	-- transform). The 17ms sleep lets OBS observe the write one frame before
	-- the game actually resizes, which is what makes the tween start clean.
	local publish_res = function(w, h)
		if not cfg.resize_animation then
			return
		end
		os.execute(string.format('echo "%dx%d" > %q', w, h, cfg.res_state_file))
		waywall.sleep(17)
	end

	-- `target_mode`, not `mode`: the outer `mode` is the live state that
	-- `refresh` reads, and shadowing it here would be a trap for later edits.
	local make_res = function(target_mode, res, sens)
		return function()
			local active_w, active_h = waywall.active_res()

			if active_w == res.w and active_h == res.h then
				publish_res(cfg.canvas.w, cfg.canvas.h)
				waywall.set_resolution(0, 0)
				-- 0 means "reset to input.sensitivity", not "freeze the camera".
				waywall.set_sensitivity(0)
				show(nil)
			else
				publish_res(res.w, res.h)
				waywall.set_resolution(res.w, res.h)
				waywall.set_sensitivity(sens or 0)
				show(target_mode)
			end
		end
	end

	----------------------------------------------------------------------
	-- Side processes
	----------------------------------------------------------------------

	local running = function(pattern)
		local handle = io.popen("pgrep -f " .. string.format("%q", pattern))
		if not handle then
			return false
		end
		local result = handle:read("*l")
		handle:close()
		return result ~= nil
	end

	local toggle_ninbot = function()
		if not running(cfg.ninb.process) then
			waywall.exec(cfg.ninb.command)
			waywall.show_floating(true)
		else
			helpers.toggle_floating()
		end
	end

	-- The CPS counter must NOT go through waywall.exec. waywall overwrites its own
	-- WAYLAND_DISPLAY with its nested socket (waywall/main.c:130), so anything it
	-- spawns connects to waywall -- and waywall implements no wlr-layer-shell, so
	-- a layer-shell client started that way finds no such protocol and silently
	-- fails to appear.
	--
	-- It has to run against the host compositor instead, which is what the
	-- configured command does (a systemd user unit, whose environment still has
	-- the host display). Being a host client is also what puts it above the
	-- waywall window rather than inside it.
	local toggle_cps = function()
		os.execute(cfg.cps.toggle_command)
	end

	local crosshair_shown = false
	local toggle_crosshair = function()
		crosshair_shown = not crosshair_shown
		scene.crosshair(crosshair_shown)
	end

	----------------------------------------------------------------------
	-- Keybinds
	----------------------------------------------------------------------

	local keys = cfg.keys

	config.actions = {
		[keys.thin] = make_res("thin", cfg.res.thin, cfg.sensitivity.thin),
		[keys.wide] = make_res("wide", cfg.res.wide, cfg.sensitivity.wide),
		[keys.tall] = make_res("tall", cfg.res.tall, cfg.sensitivity.tall),
		-- `lowest` has its own resolution and deliberately no sensitivity change:
		-- unlike tall, it is not a mode you aim in.
		[keys.lowest] = make_res("lowest", cfg.res.lowest, cfg.sensitivity.lowest),

		[keys.switch_layout] = function()
			write_layout(layout == "mcsr" and "alt" or "mcsr")
			print("switching keyboard layout; waiting for config reload")
		end,

		[keys.ninbot] = toggle_ninbot,
		[keys.cps] = toggle_cps,
		[keys.crosshair] = toggle_crosshair,
	}

	if cfg.paceman.enable then
		config.actions[keys.paceman] = function()
			if running(cfg.paceman.process) then
				print("paceman-tracker already running")
			else
				waywall.exec(cfg.paceman.command)
			end
		end
	end

	return config
end
